server:
  port: 8080

db:
  mysql:
    host: localhost
    port: 3306
    username: user
    password: pass
    database: db

log:
  level: debug
  # format: json
  format: console
  output: stdout
  # output: file
  # dir: ./logs
  # file: app.log

jwt:
  userkey: secret1
  adminkey: secret2
